<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class DBConfig {
    //define all tables

    CONST TABLE_ADMIN = 'tbl_admin';
    CONST TABLE_ADMIN_ATT_ID = 'id';
    CONST TABLE_ADMIN_ATT_USERNAME = 'username';
    CONST TABLE_ADMIN_ATT_PASSWORD = 'password';
    CONST TABLE_ADMIN_ATT_NAME = 'name';

    CONST TABLE_STAFF='tbl_staff';
    CONST TABLE_STAFF_ATT_STAFF_ID='staffId';
    CONST TABLE_STAFF_ATT_USERNAME='username';
    CONST TABLE_STAFF_ATT_PASSWORD='password';
    CONST TABLE_STAFF_ATT_STAFF_NAME='staffName';
    CONST TABLE_STAFF_ATT_IS_ACTIVE='isActive';
    
    CONST TABLE_USER='tbl_user';
    CONST TABLE_USER_ATT_USER_ID='userId';
    CONST TABLE_USER_ATT_USERNAME='username';
    CONST TABLE_USER_ATT_PASSWORD='password';
    CONST TABLE_USER_ATT_NAME='name';
    CONST TABLE_USER_ATT_ADDRESS='address';
    CONST TABLE_USER_ATT_ADDED_DATE='addedDate';
    CONST TABLE_USER_ATT_LAST_APPOINTMENT_DATE='lastAppointmentDate';
    CONST TABLE_USER_ATT_IS_ACTIVE='isActive';
    
    CONST TABLE_APPOINTMENT='tbl_appointment';
    CONST TABLE_APPOINTMENT_ATT_APPOINTMENT_ID='appointmentId';
    CONST TABLE_APPOINTMENT_ATT_APPOINTMENT_TOKEN='appointmentToken';
    CONST TABLE_APPOINTMENT_ATT_USERNAME='username';
    CONST TABLE_APPOINTMENT_ATT_DOCTOR_ID='doctorId';
    CONST TABLE_APPOINTMENT_ATT_TITLE='title';
    CONST TABLE_APPOINTMENT_ATT_DESCRIPTION='description';
    CONST TABLE_APPOINTMENT_ATT_FEE='fee';
    CONST TABLE_APPOINTMENT_ATT_APPOINTMENT_DATE='appointmentDate';
    CONST TABLE_APPOINTMENT_ATT_START_TIME='startTime';
    CONST TABLE_APPOINTMENT_ATT_END_TIME='endTime';
    CONST TABLE_APPOINTMENT_ATT_STAFF_ID='staffId';
    CONST TABLE_APPOINTMENT_ATT_STATUS='status';
    CONST TABLE_APPOINTMENT_ATT_PATIENT_STATUS='patientStatus';
    CONST TABLE_APPOINTMENT_ATT_USER_LOGGED='userLogged';
    CONST TABLE_APPOINTMENT_ATT_USER_SESSION_STRING='userSessionString';
    CONST TABLE_APPOINTMENT_ATT_IS_ADMIN_CONNECTED='isAdminConnected';
    
    CONST TABLE_DOCTOR='tbl_doctor';
    CONST TABLE_DOCTOR_ATT_DOCTOR_ID='doctorId';
    CONST TABLE_DOCTOR_ATT_USERNAME='username';
    CONST TABLE_DOCTOR_ATT_PASSWORD='password';
    CONST TABLE_DOCTOR_ATT_DOCTOR_NAME='doctorName';
    CONST TABLE_DOCTOR_ATT_ADDRESS='address';
    CONST TABLE_DOCTOR_ATT_DESIGNATION='designation';
    CONST TABLE_DOCTOR_ATT_ADDED_DATE='addedDate';
    CONST TABLE_DOCTOR_ATT_IS_ACTIVE='isActive';
    
    CONST TABLE_SETTING='tbl_setting';
    CONST TABLE_SETTING_ATT_TIMEZONE='timezone';
    
    CONST TABLE_OPENTOK_SETTINGS = "tbl_opentok_settings";
    CONST TABLE_OPENTOK_SETTINGS_ATT_API_KEY = "apiKey";
    CONST TABLE_OPENTOK_SETTINGS_ATT_SESSION_ID = "sessionId";
    CONST TABLE_OPENTOK_SETTINGS_ATT_TOKEN = "token";
    
    
}
